### PR TITLE
fix: normalize expected value in toContainHTML

### LINKED ISSUE #347: toContainHTML does not handle self-closing tags
- `@testing-library/jest-dom` version: 5.11.9 (latest)
- `node` version: n/a
- `npm` (or `yarn`) version: n/a

### Relevant code or config:

```js
import "@testing-library/jest-dom/extend-expect";
import React from "react";
import { render } from "@testing-library/react";

test("demo test", () => {
  const { container } = render(<div className="empty" />);
  // this assertion passes
  expect(container).toContainHTML('<div class="empty"></div>');
  // this one fails, even though it references the same structure
  // expect(container).toContainHTML('<div class="empty" />');  
});
```

### Reproduction:

https://codesandbox.io/s/contains-html-assertion-demo-7nd5n?file=/src/__tests__/hello.js:0-343

### Suggested solution:

toContainHTML matcher treats expected content as a string. I figured that this normalization fixes the matching:

```js
function normalize(content) {
   const div = document.createElement('div');
   div.innerHTML = content;
   return div.innerHTML;
}

expect(container).toContainHTML(normalize('<div class="empty" />'));  // passes  
```

Perhaps the matcher inside could apply this normalization

### PR DESCRIPTION
**Pull request by just-boris**
**What**:

resolve #347

**Why**:

Because this is worth fixing

**How**:

Added `getNormalizedHtml` function, that passes the content to the HTML parser.

This caused two changes in the test case with invalid HTML: `<span data-testid="child"></div>` becomes `<span data-testid="child"></span>`

**Checklist**:

- [ ] Documentation n/a
- [x] Tests
- [ ] Updated Type Definitions n/a
- [ ] Ready to be merged

### CODE REVIEW

File: src/__tests__/to-contain-html.js [hunk 1]
```diff
@@ -18,21 +18,23 @@ describe('.toContainHTML', () => {
     const nonExistantElement = queryByTestId('not-exists')
     const fakeElement = {thisIsNot: 'an html element'}
     const stringChildElement = '<span data-testid="child"></span>'
-    const incorrectStringHtml = '<span data-testid="child"></div>'
+    const stringChildElementSelfClosing = '<span data-testid="child" />'
+    // const incorrectStringHtml = '<span data-testid="child"></div>'
```
Comment (just-boris) [inline src/__tests__/to-contain-html.js:22]: The new change also normalizes this invalid HTML, so this also now passes:

```js
expect(child).toContainHTML('<span data-testid="child"></div>');  // normalized to `<span data-testid="child"></span>`
```

File: src/to-contain-html.js [hunk 2]
```diff
@@ -1,10 +1,20 @@
...
+  div.innerHTML = htmlText
+  return div.innerHTML
+}
+
 export function toContainHTML(container, htmlText) {
   checkHtmlElement(container, toContainHTML, this)
 
+  if (typeof htmlText !== 'string') {
+    throw new Error(`.toContainHTML() expects a string value, got ${htmlText}`)
+  }
```
Comment (just-boris) [inline src/to-contain-html.js:14]: Without this change, the `nonExistantElement` tests started failing. This value is basically an equivalent of `expect(element).toContainHTML(null)` which turned into a `string.includes(null)`, producing `false`. 

Now the `htmlText` always gets converted to a string, so this extra check is needed to keep the assertions failing where they were before.

**Comment by just-boris** [comment]
Opened this as a draft, as there are two maybe-major changes, see the comments above

**Comment by gnapse** [comment]
@just-boris can you take this PR to a valid non-draft state (e.g. uncomment or remove the commented code) so that I can review. I cannot get a full idea of what's going on or what you are proposing without knowing what about all that commented out code.

**Comment by just-boris** [comment]
@gnapse 
Updated the PR. It introduces two notable changes besides fixing the https://github.com/testing-library/jest-dom/issues/347

1. non-string values throw a different error now. It was an assertion error and now this is precise `.toContainHTML() expects a string value, got ${htmlText}`
2. Invalid HTML gets normalised now, passing the assertion if the result is the same as the actual content

File: src/__tests__/to-contain-html.js [hunk 3]
```diff
@@ -18,21 +18,18 @@ describe('.toContainHTML', () => {
...
     expect(child).toContainHTML(stringChildElement)
+    expect(child).toContainHTML(stringChildElementSelfClosing)
     expect(grandparent).not.toContainHTML(nonExistantString)
     expect(parent).not.toContainHTML(nonExistantString)
     expect(child).not.toContainHTML(nonExistantString)
     expect(child).not.toContainHTML(nonExistantString)
-    expect(grandparent).not.toContainHTML(incorrectStringHtml)
-    expect(parent).not.toContainHTML(incorrectStringHtml)
-    expect(child).not.toContainHTML(incorrectStringHtml)
-    expect(child).not.toContainHTML(incorrectStringHtml)
```
Comment (gnapse) [inline src/__tests__/to-contain-html.js:35]: Do we need to remove the test on the invalid html? What happens after these changes if we give invalid html like the one in this string? It'd be nice to know and add a test for that. And hopefully that what it does is still close to what one would expect.

**Review by gnapse — COMMENTED** [review]
I'm mostly OK with these changes. I left a comment on the only thing that worries me. Would like to hear what you think before merging this.

File: src/__tests__/to-contain-html.js (hunk 3 above)
Comment (just-boris) [reply src/__tests__/to-contain-html.js:35]: I agree, the tests can stay, just need to flip the direction, as this assertion now passes.

Fixed in the next revision

Comment (gnapse) [reply src/__tests__/to-contain-html.js:35]: How is it that these tests now pass? I would expect them not to pass. The rendered DOM in this test does contain the invalid html given. 🤔

Comment (just-boris) [reply src/__tests__/to-contain-html.js:35]: HTML parser ignores unmatching closing tags. Currently we have this content: `<span data-testid="child"></div>`. After normalization via `innerHTML` it becomes `<span data-testid="child"></span>` and this matches the actual content.

With normalization, this test will not pass, for example:

```js
const {container} = render(`<table>
  <tr>
    <td>test</td>
  </tr>
</table>`)
expect(container).toContainHTML('<table>test</table>');
```

`<table>test</table>` does not expand to the full table and does not match the real content

Comment (gnapse) [reply src/__tests__/to-contain-html.js:35]: Hmmm, I wonder if we could detect that, and disallow invalid html. This also makes it technically a breaking change, although I'm thinking that I'll pass on that, since it is very unlikely someone was passing invalid html to explicitly expect a failure.

I think this is good to go. Will merge soon.

**Review by gnapse — APPROVED** [review]

File: src/__tests__/to-contain-html.js (hunk 3 above)
Comment (just-boris) [reply src/__tests__/to-contain-html.js:35]: I am not sure this is possible without rolling your own parser. Built-in DOM parser does not expose enough information.

I am also wondering about the use-case here. Spotting the typos is nice, but is there any more important case where it is needed?

Comment (gnapse) [reply src/__tests__/to-contain-html.js:35]: Not really, which is why I said I approve anyway. It's just a bit unintuitive, but I agree that it makes sense since it is how html works anyway. Developing our own parser is out of the question. This matcher is anyway an outlier, in the sense that we do not recommed its use except in some unique circumstances.

**Comment by gnapse** [comment]
@all-contributors please add @just-boris for code, test, bug
